version: "3"
services:
  app:
    build: .
    container_name: springapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:6543/book_shop
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
#    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book_shop
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
